#!/usr/bin/env bash
# displays domain properties!!!
DOMAIN="$1"
SUB_DOMAIN="$2"
RECORD_TYPE="$(dig '$(SUB_DOMAIN).$(DOMAIN)' | grep '^$(SUB_DOMAIN)' | rev | cut -d$'\t' -f2)"
DESTINATION="$(dig '$(SUB_DOMAIN).$(DOMAIN)' | grep '^$(SUB_DOMAIN)' | rev | cut -d$'\t' -f1)"
echo "The subdomain $SUB_DOMAIN is a $RECORD_TYPE record and points to $DESTINATION"
