#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page
apt-get -y update && apt-get -y upgrade
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-available/default
service nginx restart
