#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
apt-get -y update && apt-get -y upgrade
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/not_found.html
service nginx start
config="server_name _;
	rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;
	page 404 /not_found.html;"
sed -i "s/server_name _;/$config/" /etc/nginx/sites-available/default
nginx -s reload
