#!/usr/bin/env bash
# Installs and configures HAproxy on "lb-01" server
apt-get -y update && apt-get -y upgrade
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo -e "\nfrontend haproxy-main
    bind *:80
    option forwardfor  
    default_backend nginx_webservers    

backend nginx_webservers
    balance roundrobin
    server 432573-web-01\t52.87.219.77:80 check
    server 432573-web-02\t3.85.1.3:80 check" >> /etc/haproxy/haproxy.cfg
#echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart
