#!/usr/bin/env bash
# Installs and configures HAproxy on "lb-01" server
apt-get -y update && apt-get -y upgrade
apt-get install -y haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo -e "\nfrontend haproxy-main
    bind *:80
    mode http 
    default_backend nginx_webservers    

backend nginx_webservers
    balance roundrobin
    server 432573-web-01\t100.26.155.232:80 check
    server 432573-web-02\t54.237.90.253:80 check" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart
