#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it
sudo mysqldump -u root -p "$1" --all-databases --result-file=backup.sql
tar -zcvf "$(date +'%d-%m-%Y')".tar.gz backup.sql
