#!/usr/bin/env bash
# displays the content of the file '/etc/passwd' w/ only (username, user id, home directory path for user)
while read -r line; do
	echo "$line" | cut -d ':' -f1,3,6
done < /etc/passwd
