#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS (story)
while IFS=$':' read -r USR PASSWD USRID GRPID GECOS HOMEDIR CMDSH; do
	echo "The user $USR is part of the $GRPID gang, lives in $HOMEDIR and rides $CMDSH. \
$USRID's place is protected by the passcode $PASSWD, more info about the user here: $GECOS"
done < /etc/passwd
