#!/usr/bin/env bash
# This script diplays numbers (1 to 20) with "bad luck" with specific number for different countries
i=1
while [ $i -le 20 ]; do
	echo $i
	case $i in
		4)
			echo "bad luck from china"
			;;
		9)
			echo "bad luck from japan"
			;;
		17)
			echo "bad luck from italy"
			;;
	esac
	i=$((i+1))
done
