#!/usr/bin/env bash
# installs ufw firewall & configures it to block all incoming traffic except 22, 80 and 443 TCP ports
apt -y update && apt -y upgrade
apt install -y ufw
ufw default deny incoming
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
