#!/usr/bin/env bash
# fixes the container so that Nginx is running as the nginx user & listens on port 8080
apt-get remove apache2
chown -R nginx.nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
